name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
     - name: 'Executar Dependency Review'
       uses: actions/dependency-review-action@v4
       with:
         fail-on-severity: high
         output: json

     - name: 'Dividir Saída em Partes'
       run: |
         split -b 900k dependency-review-report.json part_

     - name: 'Adicionar Primeira Parte ao Summary'
       run: |
         echo "### Parte 1 do Resumo" >> $GITHUB_STEP_SUMMARY
         cat part_aa >> $GITHUB_STEP_SUMMARY || true

     - name: 'Salvar Partes Restantes como Artefato'
       uses: actions/upload-artifact@v3
       with:
         name: dependency-review-parts
         path: part_*
